### PR TITLE
style: owlly-sign active

### PR DESCRIPTION
**Pull request by peterpeterparker**

### CODE REVIEW

**Comment by sansan88** [comment]
Cool! Never used it before.. is there a way for ios? as fas as I understood from reading the docs, this is for material design only?

https://ionicframework.com/docs/api/ripple-effect

**Comment by peterpeterparker** [comment]
it works for ios too

https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/ripple-effect/ripple-effect.tsx

**Comment by sansan88** [comment]
oh cool! thanks, didn't know that

**Comment by peterpeterparker** [comment]
my pleasure, the ripple effect is pretty cool

**Pull request merged**
